import Head from 'next/head'
import Headers from "../components/Header/Header"
import Home from "../components/Home/Home"


export default function Index() {
  return (
    <>
      <Head>
        <title>Chimoney Frontend Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <Home />
    </>
  )
}
